// Domain overrides for companies where the domain isn't just "companyname.com"
const DOMAIN_OVERRIDES: Record<string, string> = {
  'J.P. Morgan': 'jpmorgan.com',
  'Goldman Sachs': 'goldmansachs.com',
  'DE Shaw': 'deshaw.com',
  'Two Sigma': 'twosigma.com',
  'Bank of America': 'bankofamerica.com',
  'Walmart Labs': 'walmart.com',
  'Morgan Stanley': 'morganstanley.com',
  'Jane Street': 'janestreet.com',
  'Jump Trading': 'jumptrading.com',
  'Hudson River Trading': 'hudsonrivertrading.com',
  'Tower Research Capital': 'tower-research.com',
  'Bridgewater Associates': 'bridgewater.com',
  'Capital One': 'capitalone.com',
  'American Express': 'americanexpress.com',
  'Deutsche Bank': 'db.com',
  'Wells Fargo': 'wellsfargo.com',
  'BNY Mellon': 'bnymellon.com',
  'Palo Alto Networks': 'paloaltonetworks.com',
  'Applied Intuition': 'appliedintuition.com',
  'General Motors': 'gm.com',
  'Texas Instruments': 'ti.com',
  'Electronic Arts': 'ea.com',
  'Riot Games': 'riotgames.com',
  'Epic Systems': 'epic.com',
  'Pure Storage': 'purestorage.com',
  'Western Digital': 'westerndigital.com',
  'Arista Networks': 'arista.com',
  'GE Healthcare': 'gehealthcare.com',
  'GE Digital': 'ge.com',
  'Societe Generale': 'societegenerale.com',
  'Palantir Technologies': 'palantir.com',
  'Juniper Networks': 'juniper.net',
  'National Instruments': 'ni.com',
  Meta: 'meta.com',
  Apple: 'apple.com',
  Google: 'google.com',
  Amazon: 'amazon.com',
  Netflix: 'netflix.com',
  Microsoft: 'microsoft.com',
  Adobe: 'adobe.com',
  Uber: 'uber.com',
  Airbnb: 'airbnb.com',
  Stripe: 'stripe.com',
  Spotify: 'spotify.com',
  LinkedIn: 'linkedin.com',
  Pinterest: 'pinterest.com',
  Snap: 'snap.com',
  X: 'x.com',
  Block: 'block.xyz',
  ByteDance: 'bytedance.com',
  TikTok: 'tiktok.com',
  Nvidia: 'nvidia.com',
  Intel: 'intel.com',
  Oracle: 'oracle.com',
  SAP: 'sap.com',
  IBM: 'ibm.com',
  Cisco: 'cisco.com',
  VMware: 'vmware.com',
  Salesforce: 'salesforce.com',
  Snowflake: 'snowflake.com',
  Databricks: 'databricks.com',
  Cloudflare: 'cloudflare.com',
  PayPal: 'paypal.com',
  Visa: 'visa.com',
  Mastercard: 'mastercard.com',
  Bloomberg: 'bloomberg.com',
  Citadel: 'citadel.com',
  Robinhood: 'robinhood.com',
  Coinbase: 'coinbase.com',
  Roblox: 'roblox.com',
  Unity: 'unity.com',
  Tesla: 'tesla.com',
  Samsung: 'samsung.com',
  Sony: 'sony.com',
  Flipkart: 'flipkart.com',
  Swiggy: 'swiggy.com',
  Zomato: 'zomato.com',
  PhonePe: 'phonepe.com',
  Paytm: 'paytm.com',
  DoorDash: 'doordash.com',
  Lyft: 'lyft.com',
  Twilio: 'twilio.com',
  Intuit: 'intuit.com',
  ServiceNow: 'servicenow.com',
  Workday: 'workday.com',
  Atlassian: 'atlassian.com',
  Shopify: 'shopify.com',
  Reddit: 'reddit.com',
  Discord: 'discord.com',
  Zoom: 'zoom.us',
  Slack: 'slack.com',
  Notion: 'notion.so',
  Figma: 'figma.com',
  Dropbox: 'dropbox.com',
  Booking: 'booking.com',
  'Booking.com': 'booking.com',
  Expedia: 'expedia.com',
  Yelp: 'yelp.com',
  Zillow: 'zillow.com',
  Instacart: 'instacart.com',
  OpenAI: 'openai.com',
  Duolingo: 'duolingo.com',
  'Ola Cabs': 'olacabs.com',
  MakeMyTrip: 'makemytrip.com',
  'Urban Company': 'urbancompany.com',
  Dream11: 'dream11.com',
  CRED: 'cred.club',
  Meesho: 'meesho.com',
  Razorpay: 'razorpay.com',
  'Akuna Capital': 'akunacapital.com',
  Optiver: 'optiver.com',
  SIG: 'sig.com',
  IMC: 'imc.com',
  DRW: 'drw.com',
  Barclays: 'barclays.com',
  HSBC: 'hsbc.com',
  Citigroup: 'citi.com',
  UBS: 'ubs.com',
  BlackRock: 'blackrock.com',
  Fidelity: 'fidelity.com',
  Qualcomm: 'qualcomm.com',
  AMD: 'amd.com',
  Dell: 'dell.com',
  HP: 'hp.com',
  HPE: 'hpe.com',
  Nokia: 'nokia.com',
  Huawei: 'huawei.com',
  eBay: 'ebay.com',
  Hulu: 'hulu.com',
  Disney: 'disney.com',
  Activision: 'activision.com',
  Blizzard: 'blizzard.com',
  Valve: 'valvesoftware.com',
  Twitch: 'twitch.tv',
  'Pony.ai': 'pony.ai',
  Waymo: 'waymo.com',
  Cruise: 'getcruise.com',
  Aurora: 'aurora.tech',
  Nuro: 'nuro.ai',
  Rivian: 'rivian.com',
  'Scale AI': 'scale.com',
  'AQR Capital Management': 'aqr.com',
  'Squarepoint Capital': 'squarepoint-capital.com',
  Point72: 'point72.com',
  WorldQuant: 'worldquant.com',
  Millennium: 'mlp.com',
  'Virtu Financial': 'virtu.com',
  Anduril: 'anduril.com',
  Verkada: 'verkada.com',
  'The Trade Desk': 'thetradedesk.com',
  CrowdStrike: 'crowdstrike.com',
  Datadog: 'datadoghq.com',
  MongoDB: 'mongodb.com',
  Confluent: 'confluent.io',
  HashiCorp: 'hashicorp.com',
  Elastic: 'elastic.co',
  Okta: 'okta.com',
  Veeva: 'veeva.com',
  'Veeva Systems': 'veeva.com',
  Docusign: 'docusign.com',
  Asana: 'asana.com',
  Box: 'box.com',
  Grammarly: 'grammarly.com',
  Coursera: 'coursera.org',
  'Media.net': 'media.net',
  'Apollo.io': 'apollo.io',
  'Otter.ai': 'otter.ai',
  FreshWorks: 'freshworks.com',
  Sprinklr: 'sprinklr.com',
  Hubspot: 'hubspot.com',
  Zendesk: 'zendesk.com',
  Braze: 'braze.com',
  Samsara: 'samsara.com',
  Toast: 'toasttab.com',
  Revolut: 'revolut.com',
  Wise: 'wise.com',
  Chime: 'chime.com',
  SoFi: 'sofi.com',
  Affirm: 'affirm.com',
  Brex: 'brex.com',
  Ripple: 'ripple.com',
  Rippling: 'rippling.com',
  Rubrik: 'rubrik.com',
  Nutanix: 'nutanix.com',
  Cohesity: 'cohesity.com',
  NetApp: 'netapp.com',
  Fortinet: 'fortinet.com',
  'Poshmark': 'poshmark.com',
  Compass: 'compass.com',
  Opendoor: 'opendoor.com',
  Redfin: 'redfin.com',
  Wayfair: 'wayfair.com',
  Chewy: 'chewy.com',
  Coupang: 'coupang.com',
  Shopee: 'shopee.com',
  Grab: 'grab.com',
  Agoda: 'agoda.com',
  Tencent: 'tencent.com',
  Alibaba: 'alibaba.com',
  Baidu: 'baidu.com',
  'National Payments Corporation of India': 'npci.org.in',
  'Credit Karma': 'creditkarma.com',
  Roku: 'roku.com',
  Peloton: 'onepeloton.com',
  Nike: 'nike.com',
  Target: 'target.com',
  'Lowe\'s': 'lowes.com',
  Nordstrom: 'nordstrom.com',
  Flexport: 'flexport.com',
  Bolt: 'bolt.com',
  Wix: 'wix.com',
  Squarespace: 'squarespace.com',
  GoDaddy: 'godaddy.com',
  Akamai: 'akamai.com',
  Autodesk: 'autodesk.com',
  Siemens: 'siemens.com',
  Bosch: 'bosch.com',
  Honeywell: 'honeywell.com',
  ThoughtWorks: 'thoughtworks.com',
  Infosys: 'infosys.com',
  Wipro: 'wipro.com',
  TCS: 'tcs.com',
  tcs: 'tcs.com',
  Cognizant: 'cognizant.com',
  HCL: 'hcl.com',
  'Tech Mahindra': 'techmahindra.com',
  Capgemini: 'capgemini.com',
  Accenture: 'accenture.com',
  Deloitte: 'deloitte.com',
  EY: 'ey.com',
  McKinsey: 'mckinsey.com',
  'Thomson Reuters': 'thomsonreuters.com',
  Garmin: 'garmin.com',
  'Bentley Systems': 'bentley.com',
  Cadence: 'cadence.com',
  Synopsys: 'synopsys.com',
  KLA: 'kla.com',
  MathWorks: 'mathworks.com',
  Splunk: 'splunk.com',
  'Sumo Logic': 'sumologic.com',
  Sentry: 'sentry.io',
  'AppDynamics': 'appdynamics.com',
  'New Relic': 'newrelic.com',
  Nextdoor: 'nextdoor.com',
  Quora: 'quora.com',
  'ZipRecruiter': 'ziprecruiter.com',
  Indeed: 'indeed.com',
  Fiverr: 'fiverr.com',
  Toptal: 'toptal.com',
  UiPath: 'uipath.com',
  'EPAM Systems': 'epam.com',
  Teradata: 'teradata.com',
  Informatica: 'informatica.com',
  Cloudera: 'cloudera.com',
  FactSet: 'factset.com',
  'CME Group': 'cmegroup.com',
  MSCI: 'msci.com',
  Vanguard: 'vanguard.com',
  'DXC Technology': 'dxc.com',
  Comcast: 'comcast.com',
  Netsuite: 'netsuite.com',
  'Larsen & Toubro': 'larsentoubro.com',
  Tesco: 'tesco.com',
  Geico: 'geico.com',
  USAA: 'usaa.com',
  Arcesium: 'arcesium.com',
  razorpay: 'razorpay.com',
  blinkit: 'blinkit.com',
  jio: 'jio.com',
  Zepto: 'zeptonow.com',
  Groww: 'groww.in',
  Lenskart: 'lenskart.com',
  Hotstar: 'hotstar.com',
  Myntra: 'myntra.com',
  ShareChat: 'sharechat.com',
  Delhivery: 'delhivery.com',
  DevRev: 'devrev.ai',
  Moloco: 'moloco.com',
};

function guessDomain(name: string): string {
  if (DOMAIN_OVERRIDES[name]) return DOMAIN_OVERRIDES[name];

  // Heuristic: lowercase, remove special chars, join, add .com
  const cleaned = name
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '')
    .trim();

  return `${cleaned}.com`;
}

export function getLogoUrl(companyName: string): string {
  const domain = guessDomain(companyName);
  return `https://logo.clearbit.com/${domain}`;
}

// Generate a consistent color from company name for the fallback
export function getCompanyColor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  }
  const hue = Math.abs(hash) % 360;
  return `hsl(${hue}, 60%, 45%)`;
}

export function getCompanyInitials(name: string): string {
  const words = name.split(/[\s.]+/).filter(Boolean);
  if (words.length === 1) return words[0].substring(0, 2).toUpperCase();
  return (words[0][0] + words[1][0]).toUpperCase();
}
